import assert from 'node:assert/strict';
import { phase3Harness } from './lib/diag1Phase3Harness.mjs';
const h = await phase3Harness('DIAG1 Phase3 opportunity');
const [runner, gen, fauna, plants, plantStock, trips, exp, clock] = await Promise.all(['runner/simRunner', 'world/generate', 'agents/faunaStock', 'agents/plantPatches', 'agents/plantStock', 'agents/intraSeasonTrips', 'agents/expedition', 'tick/time'].map(h.load));
const w = gen.createVariedMigrationWorld(gen.VARIED_MIGRATION_WORLD_CONFIG), geo = fauna.deriveFaunaStockGeography(w);
const bare = r => { const { world, ...rest } = r; return rest; };
const tileId = 'tile:0:2', top = geo.byId.get('fauna:small_game:tile:0:4'), other = geo.byId.get('fauna:small_game:tile:0:0');
assert.ok(top && other && top.carryingCapacity > other.carryingCapacity, 'original overlap witness');
const depleted = { abundance: .08, disturbance: 0, lastPressureTick: 0, cumulativePressure: 0 };
const dw = { ...w, faunaStocks: { [top.id]: depleted } };
const take = (world = dw, g = geo, id = tileId, eligible = true, amount = 999, target) => fauna.resolveFaunaFoodHarvest(world, g, id, 'animal_food', world.time.season, world.time.tick, amount, eligible, target);
h.observations.originalOverlap = { tileId, top: top.id, other: other.id, receipt: bare(take()) };
await h.check('B005 exhausted static winner yields to healthy represented overlap', () => { const r = take(); assert.equal(r.sourceId, other.id); assert.ok(r.harvestedAmount > 1); assert.equal(r.depletionApplied, r.harvestedAmount); assert.deepEqual(r.world.faunaStocks[top.id], depleted); assert.equal(r.world.faunaStocks[other.id].abundance, .08); });
await h.check('B005 all exhausted / no geography / predator / activity refusal', () => { const all = { ...w, faunaStocks: Object.fromEntries(geo.stocks.map(s => [s.id, depleted])) }; assert.equal(take(all).harvestedAmount, 0); assert.equal(take(all).failureReason, 'physically_exhausted'); const empty = { ...geo, byTile: new Map() }; assert.equal(take(w, empty).failureReason, 'physical_source_absent'); const pred = { ...other, id: 'predator', trophicRole: 'predator' }; assert.equal(take(w, { ...geo, byTile: new Map([[tileId, [pred]]]) }).sourceFound, false); assert.equal(take(dw, geo, tileId, false).world, dw); });
await h.check('B005 explicit exhausted/absent source never redirects', () => { assert.equal(take(dw, geo, tileId, true, 999, top.id).harvestedAmount, 0); assert.equal(take(dw, geo, tileId, true, 999, 'fauna:missing').sourceFound, false); });
await h.check('B005 stable identity tie and repeat/overlapping geography depletion', () => { const a = { ...other, id: 'fauna:a' }, z = { ...other, id: 'fauna:z' }, g = { ...geo, byId: new Map([[a.id, a], [z.id, z]]), byTile: new Map([[tileId, [z, a, a]], ['adjacent', [a, z]]]) }; const first = take(w, g); assert.equal(first.sourceId, a.id); assert.equal(take(w, { ...g, byTile: new Map([[tileId, [a, z]]]) }).sourceId, a.id); const second = take(first.world, g, 'adjacent'); assert.equal(second.sourceId, z.id); const last = take(second.world, g); assert.equal(last.harvestedAmount, 0); });
await h.check('B005 seasonal availability retains lean floor; ineligible activity takes nothing', () => { const s = { ...other, seasonality: { peakSeasons: ['spring'], leanSeasons: ['winter'], amplitude: 1 } }; const g = { ...geo, byTile: new Map([[tileId, [s]]]) }; const peak = take(w, g); const lean = take({ ...w, time: { ...w.time, season: 'winter' } }, g); assert.ok(lean.harvestedAmount > 0 && lean.harvestedAmount < peak.harvestedAmount); assert.equal(take({ ...w, time: { ...w.time, season: 'winter' } }, g, tileId, false).harvestedAmount, 0); });
let fw = runner.initSimWorld({ kind: 'map2_single_origin' }, 'diag1b:controls');
fw = runner.stepSim(fw, 1, 'seasonal');
const band = Object.values(fw.bands)[0], template = band.resourceKnowledgeState.patchMemories[0];
const food = { ...template, patchId: 'probe-food', approximateTile: 'tile:108:54', resourceClassId: 'generic_plant_food', plantObservation: undefined, lastNotedTick: fw.time.tick, confidence: Object.fromEntries(Object.keys(template.confidence).map(k => [k, .6])), useHistory: { ...template.useHistory, lastYieldEstimate: 1, depletionMemory: 0 } };
const water = { ...food, patchId: 'probe-water', resourceClassId: 'water_resource', confidence: Object.fromEntries(Object.keys(food.confidence).map(k => [k, .4])) };
const make = mem => ({ ...band, expeditions: [], recentExpeditionOutcomes: [], pressureState: { ...band.pressureState, waterStress: .8, foodStress: .8 }, recentIntraSeasonTrips: [], resourceKnowledgeState: { ...band.resourceKnowledgeState, patchMemories: mem } });
const horizon = exp.deriveExpeditionRouteSearchHorizonTilesForAudit(fw, band, 'resource_expedition').horizonTiles;
const select = (b, world = fw) => trips.selectExpeditionTripCandidate(world, b, 96, horizon);
await h.check('B006 original food-only state launches valid distant gathering', () => { const b = make([food]), r = select(b); assert.equal(r?.memory.patchId, food.patchId); assert.ok(exp.isDistantRetrievalWorthwhileForAudit(fw, b, r, .8, exp.auditDepartable(b), Number(fw.time.tick))); assert.equal(exp.auditLaunch(fw, b, 96).expeditions[0]?.taskKind, 'distant_plant_gathering'); });
await h.check('B006 higher-scoring nonfood cannot erase food retrieval or launch', () => { const b = make([food, water]); const all = trips.auditSelect(fw, b, 96, horizon, true, false); assert.equal(all.memory.patchId, water.patchId); const r = select(b); assert.equal(r?.memory.patchId, food.patchId); assert.equal(exp.auditLaunch(fw, b, 96).expeditions[0]?.taskKind, 'distant_plant_gathering'); h.observations.foodWitness = { target: food.approximateTile, horizon, globalWinner: all.memory.patchId, foodWinner: r?.memory.patchId }; });
await h.check('B006 nonfood-only / missing target / tied foods; other task families remain eligible', () => { assert.equal(select(make([water])), undefined); assert.equal(select({ ...make([{ ...food, approximateTile: 'tile:missing' }]), knowledge: { ...band.knowledge, observedTiles: {} } }), undefined); const z = { ...food, patchId: 'z-food' }; assert.equal(select(make([z, food])).memory.patchId, 'z-food'); assert.equal(select(make([z, food])).memory.patchId, select(make([z, food])).memory.patchId); assert.equal(trips.auditSelect(fw, make([food, water]), 96, horizon, true, false).memory.patchId, water.patchId); });
await h.check('B007 Map2 all exact scout IDs belong to canonical physical top three', () => { let exact = 0, mismatch = []; for (const t of Object.values(w.tiles)) {
    for (const kind of ['plant_patch', 'fallback_food', 'material_patch', 'medicinal_toxic', 'aquatic_patch']) {
        const p = plants.derivePlantPatchesForTile(t, w.time), hint = plants.derivePlantScoutObservationHint(t, w.time, kind);
        assert.ok(p.length <= 3);
        if (hint.observedPatchId) {
            exact++;
            if (!p.some(x => x.patchId === hint.observedPatchId))
                mismatch.push({ tile: t.id, kind, physical: p.map(x => x.plantClassId), hint });
        }
    }
} h.observations.scout = { exact, mismatchCount: mismatch.length, firstMismatch: mismatch[0] }; assert.ok(exact > 0); assert.equal(mismatch.length, 0, JSON.stringify(mismatch[0])); });
await h.check('B005 returned trace identity agrees with actual chosen take/depletion', () => { const trace = fauna.deriveFaunaTripStockTrace(dw, geo, tileId, 'animal_food', w.time.season, w.time.tick); assert.equal(trace.stockId, other.id); const r = take(); assert.equal(trace.stockId, r.sourceId); assert.equal(trace.currentAbundance, 1); });
await h.check('B005 preview evaluates availability without mutating any source', () => { const before = JSON.stringify(dw); for (let i = 0; i < 3; i++)
    take(dw, geo, tileId, false); assert.equal(JSON.stringify(dw), before); });
await h.check('B006 no candidates without observed bootstrap evidence', () => { assert.equal(select({ ...make([]), knowledge: { ...band.knowledge, observedTiles: {} } }), undefined); });
await h.check('B006 stale food preserves the same selection/worth gates with nonfood added', () => { const stale = { ...food, lastNotedTick: -200, confidence: Object.fromEntries(Object.keys(food.confidence).map(k => [k, .25])) }; const a = make([stale]), b = make([stale, water]); assert.deepEqual(select(b), select(a)); assert.equal(exp.auditLaunch(fw, a, 96).expeditions.some(e => e.taskKind === 'distant_plant_gathering'), false); assert.equal(exp.auditLaunch(fw, b, 96).expeditions.some(e => e.taskKind === 'distant_plant_gathering'), false); });
await h.check('B006 contradicted/recent-empty food retains candidate but fails the unchanged worth gate', () => { const b = { ...make([food, water]), recentExpeditionOutcomes: [{ targetTileId: food.approximateTile, tick: fw.time.tick, deliveredHarvestUnits: 0, outcomeReason: 'target_absent', taskKind: 'distant_plant_gathering' }] }; const r = select(b); assert.equal(r?.memory.patchId, food.patchId); assert.equal(exp.isDistantRetrievalWorthwhileForAudit(fw, b, r, .8, exp.auditDepartable(b), Number(fw.time.tick)), false); assert.equal(exp.auditLaunch(fw, b, 96).expeditions.some(e => e.taskKind === 'distant_plant_gathering'), false); });
await h.check('B006 recent local empty visit still suppresses retrieval', () => { const b = { ...make([food, water]), recentIntraSeasonTrips: [{ targetTileId: food.approximateTile, day: 95 }] }; assert.equal(select(b), undefined); });
await h.check('B006 low remembered value remains selectable but cannot launch food work', () => { const poor = { ...food, useHistory: { ...food.useHistory, lastYieldEstimate: 0 } }; const b = make([poor, water]), r = select(b); assert.equal(r?.memory.patchId, food.patchId); assert.equal(exp.isDistantRetrievalWorthwhileForAudit(fw, b, r, .8, exp.auditDepartable(b), Number(fw.time.tick)), false); });
await h.check('B006 disconnected physical route is refused', () => { const target = { ...fw.tiles[food.approximateTile], id: 'isolated', coord: { x: fw.tiles[band.position].coord.x + 4, y: fw.tiles[band.position].coord.y }, neighbors: [] }; const ww = { ...fw, tiles: { [band.position]: { ...fw.tiles[band.position], neighbors: [] }, isolated: target } }; assert.equal(select({ ...make([{ ...food, approximateTile: 'isolated', linkedTiles: ['isolated'] }]), knowledge: { ...band.knowledge, observedTiles: {} } }, ww), undefined); });
await h.check('B006 known food selection is independent of hidden stock; absent physical take is zero', () => { const noSource = { ...fw, tiles: { ...fw.tiles, [food.approximateTile]: { ...fw.tiles[food.approximateTile], resourceProfile: { baseRichness: 0, waterAccess: 0, aquaticPotential: 0 } } } }; assert.deepEqual(select(make([food]), noSource), select(make([food]))); const r = trips.resolveExpeditionTargetWork(noSource, make([food]), food, food.approximateTile, 0, [food.approximateTile], 96, 'food_resource_check', { partyWorkers: 5 }); assert.equal(r.record.physicalFoodHarvest?.usableSupport, 0); assert.equal(r.record.physicalFoodHarvest?.physicalSourceFound, false); });
const observation = await h.load('agents/resourceScoutObservation');
const witnessTile = w.tiles['tile:99:18'];
const selectionEvidence = { candidateCount: 1, voiScore: .5, expectedInfoValue: .5, repeatPenalty: 0, targetSource: 'observed' };
const scout = (world, b, t, kind = 'plant_patch') => observation.applyResourceScoutObservation(world, b, { type: 'resource_scout', originTileId: b.position, targetTileId: t.id, scoutKind: kind, targetResourceClass: kind === 'material_patch' ? 'fuel_material' : 'generic_plant_food' }, b.knowledge, false, selectionEvidence);
await h.check('B007 material-dominated original witness cannot mint excluded leaf identity', () => { const p = plants.derivePlantPatchesForTile(witnessTile, w.time); assert.deepEqual(p.map(x => x.plantClassId), ['fuel_wood', 'fruit_berry', 'nuts_mast']); const hint = plants.derivePlantScoutObservationHint(witnessTile, w.time, 'plant_patch'); assert.notEqual(hint.observedPlantClassId, 'leaf_green'); assert.ok(!hint.observedPatchId || p.some(x => x.patchId === hint.observedPatchId)); });
await h.check('B007 physical reader / observation ordering is identical and readonly', () => { const t = witnessTile, before = JSON.stringify(w); const h1 = plants.derivePlantScoutObservationHint(t, w.time, 'plant_patch'); plantStock.resolvePlantFoodHarvest(w, t, w.time, 1, false); const h2 = plants.derivePlantScoutObservationHint(t, w.time, 'plant_patch'); assert.deepEqual(h1, h2); assert.deepEqual(plants.derivePlantPatchesForTile(t, w.time), plants.derivePlantPatchesForTile({ ...t }, w.time)); assert.equal(JSON.stringify(w), before); });
await h.check('B007 uncertain/no visible relevant patch does not fabricate an exact ID', () => { const t = { ...witnessTile, terrainKind: 'mountains', resourceProfile: { baseRichness: 0, waterAccess: 0, aquaticPotential: 0 }, riskProfile: { floodRisk: 0, droughtRisk: 1, diseaseRisk: 0 } }; const hint = plants.derivePlantScoutObservationHint(t, w.time, 'plant_patch'); assert.equal(hint.observedPatchId, undefined); assert.equal(hint.observedPlantClassId, undefined); assert.equal(hint.observationLimitReason, 'no_relevant_patch_visible'); });
await h.check('B007 low visibility preserves uncertainty; exact IDs only when justified', () => { let found; outer: for (const d of [0, 90, 180, 270])
    for (const t of Object.values(w.tiles)) {
        const hint = plants.derivePlantScoutObservationHint(t, clock.getWorldTimeForDay(d), 'plant_patch');
        if (hint.observationLimitReason === 'low_visibility_hint') {
            found = { t: t.id, hint };
            break outer;
        }
    } assert.ok(found, 'nonvacuous low-visibility observation'); assert.equal(found.hint.observedPatchId, undefined); assert.ok(found.hint.observedPlantClassId); h.observations.lowVisibility = found; });
await h.check('B007 historical false identity is not silently rewritten by physical readers', () => { const old = { ...food, approximateTile: witnessTile.id, plantObservation: { plantPatchId: `plant:${witnessTile.id}:leaf_green`, plantClassId: 'leaf_green', observationCount: 1, lastObservedTick: 0 } }; const b = make([old]), before = JSON.stringify(b); plants.derivePlantPatchesForTile(witnessTile, w.time); plants.derivePlantScoutObservationHint(witnessTile, w.time, 'plant_patch'); assert.equal(JSON.stringify(b), before); });
await h.check('B007 actual observation writes confirmation through canonical knowledge; no food/body/skill grant', () => { const t = w.tiles['tile:194:89'], b = { ...make([{ ...food, approximateTile: t.id }]), position: t.id }, before = JSON.stringify(b); const first = scout(w, b, t); const learned = first.resourceKnowledgeState?.patchMemories.find(m => m.approximateTile === t.id && m.resourceClassId === 'generic_plant_food'); assert.ok(learned?.plantObservation); const exact = learned.plantObservation.plantPatchId; assert.ok(exact); assert.ok(plants.derivePlantPatchesForTile(t, w.time).some(p => p.patchId === exact)); assert.equal(JSON.stringify(b), before); assert.deepEqual(Object.keys(first).sort(), ['debug', 'resourceKnowledgeState']); const second = scout(w, { ...b, resourceKnowledgeState: first.resourceKnowledgeState }, t); const twice = second.resourceKnowledgeState.patchMemories.find(m => m.approximateTile === t.id && m.resourceClassId === 'generic_plant_food'); assert.ok(twice.plantObservation.observationCount >= learned.plantObservation.observationCount); h.observations.knowledge = { first: first.debug, second: second.debug }; });
await h.check('B007 stale confident memory can be contradicted only by new observation', () => { const t = { ...witnessTile, resourceProfile: { baseRichness: 0, waterAccess: 0, aquaticPotential: 0 } }, ww = { ...w, tiles: { ...w.tiles, [t.id]: t } }, old = { ...food, approximateTile: t.id, lastNotedTick: -200, confidence: Object.fromEntries(Object.keys(food.confidence).map(k => [k, 1])) }, b = make([old]); const r = scout(ww, b, t); assert.equal(r.debug.plantObservation?.observedPatchId, undefined); assert.ok(r.resourceKnowledgeState !== b.resourceKnowledgeState); const m = r.resourceKnowledgeState.patchMemories.find(m => m.approximateTile === t.id && m.resourceClassId === 'generic_plant_food'); assert.ok(m.learning?.contradictionCount > 0 || m.learning?.lastOutcome === 'plant_patch_not_confirmed'); h.observations.contradiction = { learning: m.learning, debug: r.debug }; });
await h.finish();
